### PR TITLE
feat: update to new tables that include sorting and filtering

### PR DESCRIPTION
**Pull request by davidma415**
### Summary
This updates our app file to be the latest for 2.8 - which will include the sorting / pagination / filtering for tables.

- Applications List Table
- Application Credentials Table
- Application Services Table
- API Credentials Table

### Implementations

1.
2.
3.
4.

### Changed Docs

1.
2.
3.
4.

### Issues Resolved

1.
2.
3.
4.

### CODE REVIEW

**Comment by Mierenga** [comment]
Thanks for being proactive on this, let's make sure we use the `build:prod` script to fully minify the app file before we merge this.

**Comment by nateslo** [comment]
Yep, looks like the app file is not minified

**Comment by davidma415** [comment]
@Mierenga @nateslo yep! Will do that once we have all the changes we need in :)

**Comment by davidma415** [comment]
So the tests currently aren't passing on the filtering when running through CI - but this is due to the `kong-ee` changes not being merged yet.

**Review by Mierenga — APPROVED** [review]
Tested this build locally, everything looks good

**Pull request merged**
