### PR TITLE
YAML based main menu

### PR DESCRIPTION
**Pull request by svenwal**
### Summary

This pull request rewrites the the menu bar on the default dev portal to not being a hard coded HTML but instead it is completely rendered out of a YAML file (portal.yaml.conf).

Additionally I have added the following features:
- roles are used - dynamic menu based on who logs in
- sub_menus are part of the yaml (and from the structure this could be sub_menu in sub_menu and so on as it is recursive)
- custom css styles can be inserted (used for the button)

### Implementations

1. the given portal.yaml.conf has been with two new entries: menu and menu_no_auth
2. the given header.html has been simplified to include a menu.html template
3. the new menu.html (called recursively) generates the menu

The following parameters are available in the portal.yaml.conf

- title: (string) display title of the menu entry
- dynamic_title: (string, name of lua function) executes template code to generate the title (used for user.get("email")
- url: (string) url the menu points to
- needs_auth: (boolean) when set to true menu entry only shown if logged in
- needs_role: (string) menu entry only shown if user is logged in AND is in the given role
- hide_when_authenticated: (boolean) entry is hidden if user is logged in (used for Sign Up and Login entries)
- css_classes: (array of strings): css classes to be attached to the menu entry
- sub_menu: (array of menu entries) creates a submenu  

### Changed Docs

1. the docs on this are missing until now

### Issues Resolved

1. menus can now be updated in a CI/CD chain much easier
2. roles where not being considered in original template

### CODE REVIEW

**Comment by svenwal** [comment]
Any update on this?

**Comment by svenwal** [comment]
Just wanted to ask if this PR is interesting or I shall abandon it?

**Comment by HenriPro** [comment]
Sorry for the lack of response on this. I am a fan of the idea of this PR!, while I don't think we can get in to this in time for the very next EE release, I would like to see this get merged in. We will be setting aside some time to review this.

**Comment by aaronhmiller** [comment]
This would come in handy for the field and customers. Seeing increasing desire to customize the Portal and tying content changes to Roles.

**Review by HenriPro — APPROVED** [review]
Took a thorough run through this PR. Super neat! 

Sorry have not had a chance to merge this sooner. I don't see any issue with this, lets get this merged.

**Review by nateslo — APPROVED** [review]
LGTM

**Pull request merged**
